name: Compressed Size

on: [pull_request]

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.1
          run_install: false
      - uses: actions/checkout@v3
      - uses: preactjs/compressed-size-action@2.5.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'build:packages'
